SELECT
  MARTYRS.MARTYR_NAME,
  MARTYRS.MARTYR_DOB,
  MARTYRS.MARTYR_DATE_OF_MARTYRDOM,
  MARTYRS.MARTYR_GRAVE_LOCATION,
  BATTLES.BATTLE_NAME,
  BATTLES.BATTLE_PLACE,
  BATTLES.BATTLE_DATE,
  WAR_CRIMINAL.NAME,
  WAR_CRIMINAL.NATIONALITY
FROM BATTLES JOIN
  MARTYRS_BATTLES ON BATTLES.BATTLE_NAME = MARTYRS_BATTLES.BATTLE_NAME
JOIN MARTYRS ON MARTYRS_BATTLES.MARTYR_ID = MARTYRS.MARTYR_ID
JOIN MARTYRS_WAR_CRIMINAL ON MARTYRS.MARTYR_ID = MARTYRS_WAR_CRIMINAL.MARTYR_ID
JOIN WAR_CRIMINAL ON MARTYRS_WAR_CRIMINAL.WAR_CRIMINAL_ID
                     = WAR_CRIMINAL.WAR_CRIMINAL_ID

;