SELECT
 EMPLOYEE.EMPLOYEE_ID,EMPLOYEE_NAME,DONATION_AMMOUNT

FROM EMPLOYEE JOIN EMPLOYEE_DONORS ON
  EMPLOYEE.EMPLOYEE_ID = EMPLOYEE_DONORS.EMPLOYEE_ID
JOIN DONORS ON EMPLOYEE_DONORS.TICKET_NO = DONORS.TICKET_NO
;