SELECT
  CONTRIBUTOR_NAME,ORGANIZATION_NAME,CONTRUBITOR_DOB,
  PROFESSION,ARTIFACT_NAME,ARTIFACT_CATEGORY
FROM CONTRIBUTORS JOIN  ARTIFACTS_CONTRIBUTORS
    ON CONTRIBUTORS.NID = ARTIFACTS_CONTRIBUTORS.NID
JOIN ARTIFACTS ON ARTIFACTS_CONTRIBUTORS.ARTIFACT_ID = ARTIFACTS.ARTIFACT_ID

;