SELECT
  count(FREEDOM_FIGHTERS.FREEDOM_FIGHTER_ID),
  SECTOR.SECTOR_COMMANDAR,SECTOR.SECTOR_INDEPENDANCE_DATE
FROM FREEDOM_FIGHTERS
JOIN FREEDOM_FIGHTERS_SECTOR ON FREEDOM_FIGHTERS.FREEDOM_FIGHTER_ID =
                                FREEDOM_FIGHTERS_SECTOR.FREEDOM_FIGHTER_ID
  JOIN SECTOR ON FREEDOM_FIGHTERS_SECTOR.SECTOR_NO = SECTOR.SECTOR_NO
  WHERE SECTOR_COMMANDAR  IN (SELECT
                              SECTOR_COMMANDAR FROM SECTOR);